use regex::Regex;
use serde::Serialize;
use serde_yaml;
use std::fs;

#[derive(Debug, Serialize)]
struct OscDoc {
    osc_address: String,
    params: Vec<OscArgOrParam>,
    arguments: Vec<OscArgOrParam>,
    access_tags: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    comments: Vec<String>,
}

#[derive(Debug, Serialize)]
struct OscArgOrParam {
    name: String,
    r#type: String,
    description: String,
}

const YAML_HEADER: &str = r#"
# This file is autogenerated. Do not edit directly.
# Generated by reaper-arpad/tools/oscdoc
#
# This file contains OSC documentation extracted from the source code defining the OSC routes exposed by reaper-arpad.
#
# Each entry defines an Open Sound Control (OSC) route and specifies the OSC address, parameters, arguments, access flags, and any additional comments.
#
# Generally, each OSC route accepts or transmits a single argument, although this is not strictly enforced.
#
# Routes may also include parameters encoded within the address itself, denoted by `{}`-delimited placeholders. These parameters are defined in a `params` section.
# Callers should replace these placeholders with appropriate values when constructing OSC messages.
# The following parameter types are supported:
# - int: 32-bit integer
# - string: UTF-8 string
#
# Routes may be used in 3 ways, each of which is indicated by a corresponding access tag:
# 1. readable: The route transmits data FROM the application. The client can listen for messages on this route.
#   When Reaper sends these messages, their placeholders will be populated.

# 2. writeable: The route accepts data TO the application. The client can send messages to this route.
#   It is the client's responsibility to populate the placeholders with appropriate values.
#   Whatever argument the client passes will be the new value set within Reaper.
#   NOTE: writeable does NOT imply readable.

# 3. queryable: The route supports querying, which prompts the application to send the current value back to the client along this route.
#   To query a route, append `?` to the end of the address. Any arguments are discarded when querying. Reaper will respond on the readable version of this route (WITHOUT appending `?`).
#   Parameters are still required in the address when querying (whenever the route includes placeholders).
#   NOTE: queryable implies readable.
"#;

/// Tool to extract OSC documentation from Rust source code and output as YAML.
///
/// Osc documentation is formatted as formatted doc comments preceding
/// the function definition, starting with a line containing `@osc-doc`.
///
/// Osc routes are composed of an address and zero or more arguments. Arguments may be of the
/// following types:
/// - int: 32-bit integer
/// - float: 32-bit float
/// - string: UTF-8 string
/// - bool: boolean
///
/// Practically, each route typically accepts or receives a single argument, although this is not strictly
/// enforced.
///
/// Incorrect argument types are ignored.
///
/// Minimal example:
/// /// @osc-doc
/// /// This function does something important.
/// /// OSC Address: /example/address
/// /// - args:
/// ///   - arg (int): The first argument.
///
/// Osc addresses are specified on a line starting with `OSC Address:`.
///
/// Frequently, OSC routes encode information within the route itself. These parameters are defiend
/// in a `params` section. Parameters are typed and then encoded into the route in place of
/// `{}`-delimited placeholders.
///
/// Parameters may be of the following types:
/// - int: 32-bit integer
/// - string: UTF-8 string
///
/// In addition, routes are marked with one or more of the following accessibility tags:
/// - @readable: The route transmits data FROM the application. The client can listen for messages on this route.
/// - @writeable: The route accepts data TO the application. The client can send messages to this route.
///   @writeable does NOT imply @readable.
/// - @queryable: The route supports querying, which prompts the application to send the current value back to the client along this route.
///   To query a route, append `?` to the end of the address. Any arguments are discarded when querying. The application responds to the route WITHOUT appending `?`.
///   Parameters are still required in the address when querying (whenever the route includes placeholders).
///   @queryable implies @readable.
///
/// Routes no tags have no effect.
///
/// Any additional comments preceding the `OSC Address:` line are collected as general comments and
/// preserved in the output yaml file.
///
/// Example:
/// /// @osc-doc
/// /// @writeable
/// /// @readable
/// /// @queryable
/// /// Sets the value of a track FX parameter.
/// /// OSC Address: /track/{track_guid}/fx/{fx_index}/param/{param_index}/value
/// /// - params:
/// ///   - track_guid (string): The GUID of the track.
/// ///   - fx_index (int): The index of the FX on the track.
/// ///   - param_index (int): The index of the parameter on the FX.
/// /// - args:
/// ///   - value (float): The value of the parameter
///
/// Example output (YAML):
/// - osc_address: /track/{track_guid}/fx/{fx_index}/param/{param_index}/value
///   comments:
///   - Sets the value of a track FX parameter.
///   params:
///   - name: track_guid
///     type: string
///     description: unique identifier for the track
///   - name: fx_index
///     type: int
///     description: index of the FX on the track
///   - name: param_index
///     type: int
///     description: index of the parameter on the FX
///   args:
///   - name: value
///     type: float
///     description: The value of the parameter
///   access:
///   - readable
///   - writeable
///   - queryable
fn parse_doc_block(input: &str) -> Vec<OscDoc> {
    let re = Regex::new(r"(?s)/// ?@osc-doc\n(.*?)(?:fn (\w+)[^\n]*\{)").unwrap();
    let osc_re = Regex::new(r"^.*///\s*OSC Address:\s*(.*)$").unwrap();
    let arg_re = Regex::new(r"^.*///\s*-\s*(\w+)\s*\((\w+)\):\s*(.*)$").unwrap();
    let section_re = Regex::new(r"^.*///\s*-\s*(params|args):\s*$").unwrap();

    let mut docs = Vec::new();

    for cap in re.captures_iter(input) {
        let docblock = &cap[1];

        let mut comments = Vec::new();
        let mut osc_address = None;
        let mut params = Vec::new();
        let mut arguments = Vec::new();
        let mut access_tags = Vec::new();

        let mut in_osc_section = false;
        let mut current_section = None;

        for line in docblock.lines() {
            if line.contains("@readable") {
                access_tags.push("readable".to_string());
                continue;
            }
            if line.contains("@writeable") {
                access_tags.push("writeable".to_string());
                continue;
            }
            if line.contains("@queryable") {
                access_tags.push("queryable".to_string());
                continue;
            }

            if osc_re.is_match(line) {
                osc_address = Some(osc_re.captures(line).unwrap()[1].to_string());
                in_osc_section = true;
                continue;
            }

            if in_osc_section {
                if let Some(section_cap) = section_re.captures(line) {
                    current_section = Some(section_cap[1].to_string());
                    continue;
                }

                if let Some(arg_cap) = arg_re.captures(line) {
                    let entry = OscArgOrParam {
                        name: arg_cap[1].to_string(),
                        r#type: arg_cap[2].to_string(),
                        description: arg_cap[3].to_string(),
                    };

                    match current_section.as_deref() {
                        Some("params") => params.push(entry),
                        Some("args") => arguments.push(entry),
                        None => arguments.push(entry),
                        _ => arguments.push(entry),
                    }
                }
            } else {
                let cleaned = line.trim_start_matches("///").trim().to_string();
                if !cleaned.is_empty() {
                    comments.push(cleaned);
                }
            }
        }

        docs.push(OscDoc {
            osc_address: osc_address.unwrap_or_default(),
            params,
            arguments,
            access_tags,
            comments,
        });
    }

    docs
}
fn main() {
    let src = fs::read_to_string("src/osc_routes.rs").expect("No src/lib.rs found");
    let docs = parse_doc_block(&src);

    // Output header and yaml
    let yaml = serde_yaml::to_string(&docs).unwrap();
    let output = format!("{}\n{}", YAML_HEADER.trim(), yaml);
    fs::write("osc_docs.yaml", output).unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_minimal_doc() {
        let input = r#"
/// @osc-doc
/// This function does something important.
/// OSC Address: /example/address
/// - args:
///   - arg (int): The first argument.
fn example_function() {
"#;
        let docs = parse_doc_block(input);
        assert_eq!(docs.len(), 1);
        assert_eq!(docs[0].osc_address, "/example/address");
        assert_eq!(
            docs[0].comments,
            vec!["This function does something important."]
        );
        assert_eq!(docs[0].arguments.len(), 1);
        assert_eq!(docs[0].arguments[0].name, "arg");
        assert_eq!(docs[0].arguments[0].r#type, "int");
        assert_eq!(docs[0].arguments[0].description, "The first argument.");
        assert_eq!(docs[0].params.len(), 0);
        assert_eq!(docs[0].access_tags.len(), 0);
    }

    #[test]
    fn test_with_readable_tag() {
        let input = r#"
/// @osc-doc
/// @readable
/// Sends data from the application.
/// OSC Address: /output/data
/// - args:
///   - value (float): The data value.
fn send_data() {
"#;
        let docs = parse_doc_block(input);
        assert_eq!(docs.len(), 1);
        assert_eq!(docs[0].osc_address, "/output/data");
        assert_eq!(docs[0].access_tags, vec!["readable"]);
        assert_eq!(docs[0].comments, vec!["Sends data from the application."]);
    }

    #[test]
    fn test_with_writeable_tag() {
        let input = r#"
/// @osc-doc
/// @writeable
/// Accepts input to the application.
/// OSC Address: /input/data
/// - args:
///   - value (float): The input value.
fn receive_data() {
"#;
        let docs = parse_doc_block(input);
        assert_eq!(docs.len(), 1);
        assert_eq!(docs[0].access_tags, vec!["writeable"]);
    }

    #[test]
    fn test_with_queryable_tag() {
        let input = r#"
/// @osc-doc
/// @queryable
/// @readable
/// Supports querying for current value.
/// OSC Address: /query/value
/// - args:
///   - current (int): The current value.
fn queryable_route() {
"#;
        let docs = parse_doc_block(input);
        assert_eq!(docs.len(), 1);
        assert_eq!(docs[0].access_tags, vec!["queryable", "readable"]);
    }

    #[test]
    fn test_with_all_access_tags() {
        let input = r#"
/// @osc-doc
/// @readable
/// @writeable
/// @queryable
/// Route with all access modes.
/// OSC Address: /full/access
/// - args:
///   - value (float): The value.
fn full_access() {
"#;
        let docs = parse_doc_block(input);
        assert_eq!(docs.len(), 1);
        assert_eq!(
            docs[0].access_tags,
            vec!["readable", "writeable", "queryable"]
        );
    }

    #[test]
    fn test_with_params_and_args() {
        let input = r#"
/// @osc-doc
/// @writeable
/// @readable
/// @queryable
/// Sets the value of a track FX parameter.
/// OSC Address: /track/{track_guid}/fx/{fx_index}/param/{param_index}/value
/// - params:
///   - track_guid (string): The GUID of the track.
///   - fx_index (int): The index of the FX on the track.
///   - param_index (int): The index of the parameter on the FX.
/// - args:
///   - value (float): The value of the parameter
fn set_fx_param() {
"#;
        let docs = parse_doc_block(input);
        assert_eq!(docs.len(), 1);
        assert_eq!(
            docs[0].osc_address,
            "/track/{track_guid}/fx/{fx_index}/param/{param_index}/value"
        );
        assert_eq!(docs[0].params.len(), 3);
        assert_eq!(docs[0].params[0].name, "track_guid");
        assert_eq!(docs[0].params[0].r#type, "string");
        assert_eq!(docs[0].params[1].name, "fx_index");
        assert_eq!(docs[0].params[1].r#type, "int");
        assert_eq!(docs[0].params[2].name, "param_index");
        assert_eq!(docs[0].params[2].r#type, "int");
        assert_eq!(docs[0].arguments.len(), 1);
        assert_eq!(docs[0].arguments[0].name, "value");
        assert_eq!(docs[0].arguments[0].r#type, "float");
        assert_eq!(
            docs[0].access_tags,
            vec!["writeable", "readable", "queryable"]
        );
    }

    #[test]
    fn test_multiple_params() {
        let input = r#"
/// @osc-doc
/// @writeable
/// Multiple parameters in address.
/// OSC Address: /device/{device_id}/channel/{channel}/setting/{setting_name}
/// - params:
///   - device_id (int): Device identifier.
///   - channel (int): Channel number.
///   - setting_name (string): Name of the setting.
/// - args:
///   - value (string): The setting value.
fn set_device_setting() {
"#;
        let docs = parse_doc_block(input);
        assert_eq!(docs.len(), 1);
        assert_eq!(docs[0].params.len(), 3);
        assert_eq!(docs[0].arguments.len(), 1);
    }

    #[test]
    fn test_multiple_args() {
        let input = r#"
/// @osc-doc
/// @writeable
/// Multiple arguments.
/// OSC Address: /complex/route
/// - args:
///   - x (float): X coordinate.
///   - y (float): Y coordinate.
///   - z (float): Z coordinate.
fn complex_route() {
"#;
        let docs = parse_doc_block(input);
        assert_eq!(docs.len(), 1);
        assert_eq!(docs[0].arguments.len(), 3);
        assert_eq!(docs[0].arguments[0].name, "x");
        assert_eq!(docs[0].arguments[1].name, "y");
        assert_eq!(docs[0].arguments[2].name, "z");
    }

    #[test]
    fn test_only_params_no_args() {
        let input = r#"
/// @osc-doc
/// @readable
/// Route with only parameters, no arguments.
/// OSC Address: /track/{track_id}/name
/// - params:
///   - track_id (int): The track ID.
fn get_track_name() {
"#;
        let docs = parse_doc_block(input);
        assert_eq!(docs.len(), 1);
        assert_eq!(docs[0].params.len(), 1);
        assert_eq!(docs[0].arguments.len(), 0);
    }

    #[test]
    fn test_multiple_comments() {
        let input = r#"
/// @osc-doc
/// @writeable
/// This is the first comment line.
/// This is the second comment line.
/// And a third one for good measure.
/// OSC Address: /multi/comment
/// - args:
///   - data (string): Some data.
fn multi_comment() {
"#;
        let docs = parse_doc_block(input);
        assert_eq!(docs.len(), 1);
        assert_eq!(docs[0].comments.len(), 3);
        assert_eq!(docs[0].comments[0], "This is the first comment line.");
        assert_eq!(docs[0].comments[1], "This is the second comment line.");
        assert_eq!(docs[0].comments[2], "And a third one for good measure.");
    }

    #[test]
    fn test_empty_comments_filtered() {
        let input = r#"
/// @osc-doc
/// @readable
///
/// This has an empty line above.
///
/// OSC Address: /empty/lines
/// - args:
///   - value (int): A value.
fn empty_lines() {
"#;
        let docs = parse_doc_block(input);
        assert_eq!(docs.len(), 1);
        // Empty lines should not be included in comments
        assert_eq!(docs[0].comments, vec!["This has an empty line above."]);
    }

    #[test]
    fn test_no_access_tags() {
        let input = r#"
/// @osc-doc
/// Route without access tags.
/// OSC Address: /no/access
/// - args:
///   - value (bool): A boolean value.
fn no_access() {
"#;
        let docs = parse_doc_block(input);
        assert_eq!(docs.len(), 1);
        assert_eq!(docs[0].access_tags.len(), 0);
    }

    #[test]
    fn test_various_arg_types() {
        let input = r#"
/// @osc-doc
/// @writeable
/// Tests various argument types.
/// OSC Address: /types/test
/// - args:
///   - int_val (int): An integer.
///   - float_val (float): A float.
///   - string_val (string): A string.
///   - bool_val (bool): A boolean.
fn type_test() {
"#;
        let docs = parse_doc_block(input);
        assert_eq!(docs.len(), 1);
        assert_eq!(docs[0].arguments.len(), 4);
        assert_eq!(docs[0].arguments[0].r#type, "int");
        assert_eq!(docs[0].arguments[1].r#type, "float");
        assert_eq!(docs[0].arguments[2].r#type, "string");
        assert_eq!(docs[0].arguments[3].r#type, "bool");
    }

    #[test]
    fn test_backward_compatibility_args_without_section() {
        let input = r#"
/// @osc-doc
/// Old style without explicit args section.
/// OSC Address: /old/style
///   - value (int): A value defined without section header.
fn old_style() {
"#;
        let docs = parse_doc_block(input);
        assert_eq!(docs.len(), 1);
        // Should default to arguments
        assert_eq!(docs[0].arguments.len(), 1);
        assert_eq!(docs[0].arguments[0].name, "value");
    }

    #[test]
    fn test_yaml_serialization() {
        let doc = OscDoc {
            osc_address: "/test/address".to_string(),
            params: vec![OscArgOrParam {
                name: "param1".to_string(),
                r#type: "int".to_string(),
                description: "First param".to_string(),
            }],
            arguments: vec![OscArgOrParam {
                name: "arg1".to_string(),
                r#type: "float".to_string(),
                description: "First arg".to_string(),
            }],
            access_tags: vec!["readable".to_string(), "writeable".to_string()],
            comments: vec!["Test comment".to_string()],
        };

        let yaml = serde_yaml::to_string(&vec![doc]).unwrap();
        assert!(yaml.contains("osc_address: /test/address"));
        assert!(yaml.contains("params:"));
        assert!(yaml.contains("arguments:"));
        assert!(yaml.contains("access_tags:"));
        assert!(yaml.contains("comments:"));
        assert!(yaml.contains("- readable"));
        assert!(yaml.contains("- writeable"));
    }

    #[test]
    fn test_empty_comments_field_not_serialized() {
        let doc = OscDoc {
            osc_address: "/test".to_string(),
            params: vec![],
            arguments: vec![],
            access_tags: vec![],
            comments: vec![],
        };

        let yaml = serde_yaml::to_string(&vec![doc]).unwrap();
        // Empty comments should not appear in YAML due to skip_serializing_if
        assert!(!yaml.contains("comments:"));
    }
}
